services:
    # 后端服务
    grp-speed-backend:
        build:
            context: .
            dockerfile: backend/Dockerfile # 指向后端的 Dockerfile 路径
        image: ghcr.io/starfreedomx/garupa-speed-tracker-backend:latest
        container_name: garupa-speed-backend
        restart: always
        env_file:
            - ./backend/.env
        environment:
            - HOST=0.0.0.0
            - PORT=5519
            - MONGODB_URI=mongodb://grp-speed-mongodb:27017
            - MONGODB_DB=garupa
        volumes:
            - grp-speed-data:/app/data
        depends_on:
            - grp-speed-mongodb

    # MongoDB
    grp-speed-mongodb:
        image: mongo:7
        container_name: garupa-speed-mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    # 前端服务
    grp-speed-frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile # 指向前端的 Dockerfile 路径
        image: ghcr.io/starfreedomx/garupa-speed-tracker-frontend:latest
        container_name: garupa-speed-frontend
        restart: always
        ports:
            - "5913:5913"
        depends_on:
            - grp-speed-backend
            - grp-speed-mongodb


volumes:
    mongo-data:
    grp-speed-data:
